
CREATE TYPE public.account_type AS ENUM (
    'Client',
    'Employee',
    'Admin'
);


ALTER TYPE public.account_type OWNER TO gabriel;

--
-- TOC entry 857 (class 1247 OID 16399)
-- Name: sample; Type: TYPE; Schema: public; Owner: gabriel
--

CREATE TYPE public.sample AS ENUM (
    'first-value',
    'second-value',
    'third-value'
);


ALTER TYPE public.sample OWNER TO gabriel;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 16448)
-- Name: account; Type: TABLE; Schema: public; Owner: gabriel
--

CREATE TABLE public.account (
    account_id integer NOT NULL,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type public.account_type DEFAULT 'Client'::public.account_type NOT NULL
);


ALTER TABLE public.account OWNER TO gabriel;

--
-- TOC entry 223 (class 1259 OID 16447)
-- Name: account_account_id_seq; Type: SEQUENCE; Schema: public; Owner: gabriel
--

ALTER TABLE public.account ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16406)
-- Name: classification; Type: TABLE; Schema: public; Owner: gabriel
--

CREATE TABLE public.classification (
    classification_id integer NOT NULL,
    classification_name character varying NOT NULL
);


ALTER TABLE public.classification OWNER TO gabriel;

--
-- TOC entry 219 (class 1259 OID 16405)
-- Name: classification_classification_id_seq; Type: SEQUENCE; Schema: public; Owner: gabriel
--

ALTER TABLE public.classification ALTER COLUMN classification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.classification_classification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16417)
-- Name: inventory; Type: TABLE; Schema: public; Owner: gabriel
--

CREATE TABLE public.inventory (
    inv_id integer NOT NULL,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9,0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL
);


ALTER TABLE public.inventory OWNER TO gabriel;

--
-- TOC entry 221 (class 1259 OID 16416)
-- Name: inventory_inv_id_seq; Type: SEQUENCE; Schema: public; Owner: gabriel
--

ALTER TABLE public.inventory ALTER COLUMN inv_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_inv_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3405 (class 0 OID 16448)
-- Dependencies: 224
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: gabriel
--



--
-- TOC entry 3401 (class 0 OID 16406)
-- Dependencies: 220
-- Data for Name: classification; Type: TABLE DATA; Schema: public; Owner: gabriel
--

INSERT INTO public.classification VALUES (1, 'Custom') ON CONFLICT DO NOTHING;
INSERT INTO public.classification VALUES (2, 'Sport') ON CONFLICT DO NOTHING;
INSERT INTO public.classification VALUES (3, 'SUV') ON CONFLICT DO NOTHING;
INSERT INTO public.classification VALUES (4, 'Truck') ON CONFLICT DO NOTHING;
INSERT INTO public.classification VALUES (5, 'Sedan') ON CONFLICT DO NOTHING;


--
-- TOC entry 3403 (class 0 OID 16417)
-- Dependencies: 222
-- Data for Name: inventory; Type: TABLE DATA; Schema: public; Owner: gabriel
--

INSERT INTO public.inventory VALUES (1, 'Chevy', 'Camaro', '2018', 'If you want to look cool this is the ar you need! This car has great performance at an affordable price. Own it today!', '/images/vehicles/camaro.jpg', '/images/vehicles/camaro-tn.jpg', 25000, 101222, 'Silver', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (2, 'Batmobile', 'Custom', '2007', 'Ever want to be a super hero? now you can with the batmobile. This car allows you to switch to bike mode allowing you to easily maneuver through traffic during rush hour.', '/images/vehicles/batmobile.jpg', '/images/vehicles/batmobile-tn.jpg', 65000, 29887, 'Black', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (3, 'FBI', 'Surveillance Van', '2016', 'Do you like police shows? You will feel right at home driving this van, comes complete with survalence equipments for and extra fee of $2,000 a month.', '/images/vehicles/survan.jpg', '/images/vehicles/survan-tn.jpg', 20000, 19851, 'Brown', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (4, 'Dog ', 'Car', '1997', 'Do you like dogs? Well this car is for you straight from the 90s from Aspen, Colorado we have the orginal Dog Car complete with fluffy ears.', '/images/vehicles/dog-car.jpg', '/images/vehicles/dog-car-tn.jpg', 35000, 71632, 'White', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (5, 'Jeep', 'Wrangler', '2019', 'The Jeep Wrangler is small and compact with enough power to get you where you want to go. Its great for everyday driving as well as offroading weather that be on the the rocks or in the mud!', '/images/vehicles/wrangler.jpg', '/images/vehicles/wrangler-tn.jpg', 28045, 41205, 'Yellow', 3) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (6, 'Lamborghini', 'Adventador', '2016', 'This V-12 engine packs a punch in this sporty car. Make sure you wear your seatbelt and obey all traffic laws. ', '/images/vehicles/adventador.jpg', '/images/vehicles/adventador-tn.jpg', 417650, 71003, 'Blue', 2) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (7, 'Aerocar International', 'Aerocar', '1963', 'Are you sick of rushhour trafic? This car converts into an airplane to get you where you are going fast. Only 6 of these were made, get them while they last!', '/images/vehicles/aerocar.jpg', '/images/vehicles/aerocar-tn.jpg', 700000, 18956, 'Red', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (8, 'Monster', 'Truck', '1995', 'Most trucks are for working, this one is for fun. This beast comes with 60 inch tires giving you traction needed to jump and roll in the mud.', '/images/vehicles/monster-truck.jpg', '/images/vehicles/monster-truck-tn.jpg', 150000, 3998, 'purple', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (9, 'Cadillac', 'Escalade', '2019', 'This stylin car is great for any occasion from going to the beach to meeting the president. The luxurious inside makes this car a home away from home.', '/images/vehicles/escalade.jpg', '/images/vehicles/escalade-tn.jpg', 75195, 41958, 'Black', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (11, 'Mechanic', 'Special', '1964', 'Not sure where this car came from. however with a little tlc it will run as good a new.', '/images/vehicles/mechanic.jpg', '/images/vehicles/mechanic-tn.jpg', 100, 200125, 'Rust', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (12, 'Ford', 'Model T', '1921', 'The Ford Model T can be a bit tricky to drive. It was the first car to be put into production. You can get it in any color you want as long as it is black.', '/images/vehicles/model-t.jpg', '/images/vehicles/model-t-tn.jpg', 30000, 26357, 'Black', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (13, 'Mystery', 'Machine', '1999', 'Scooby and the gang always found luck in solving their mysteries because of there 4 wheel drive Mystery Machine. This Van will help you do whatever job you are required to with a success rate of 100%.', '/images/vehicles/mystery-van.jpg', '/images/vehicles/mystery-van-tn.jpg', 10000, 128564, 'Green', 1) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (14, 'Spartan', 'Fire Truck', '2012', 'Emergencies happen often. Be prepared with this Spartan fire truck. Comes complete with 1000 ft. of hose and a 1000 gallon tank.', '/images/vehicles/fire-truck.jpg', '/images/vehicles/fire-truck-tn.jpg', 50000, 38522, 'Red', 4) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (15, 'Ford', 'Crown Victoria', '2013', 'After the police force updated their fleet these cars are now available to the public! These cars come equiped with the siren which is convenient for college students running late to class.', '/images/vehicles/crwn-vic.jpg', '/images/vehicles/crwn-vic-tn.jpg', 10000, 108247, 'White', 5) ON CONFLICT DO NOTHING;
INSERT INTO public.inventory VALUES (10, 'GM', 'Hummer', '2016', 'Do you have 6 kids and like to go offroading? The Hummer gives you the a huge interior with an engine to get you out of any muddy or rocky situation.', '/images/vehicles/hummer.jpg', '/images/vehicles/hummer-tn.jpg', 58800, 56564, 'Yellow', 4) ON CONFLICT DO NOTHING;


--
-- TOC entry 3413 (class 0 OID 0)
-- Dependencies: 223
-- Name: account_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gabriel
--

SELECT pg_catalog.setval('public.account_account_id_seq', 1, true);


--
-- TOC entry 3414 (class 0 OID 0)
-- Dependencies: 219
-- Name: classification_classification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gabriel
--

SELECT pg_catalog.setval('public.classification_classification_id_seq', 5, true);


--
-- TOC entry 3415 (class 0 OID 0)
-- Dependencies: 221
-- Name: inventory_inv_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gabriel
--

SELECT pg_catalog.setval('public.inventory_inv_id_seq', 15, true);


--
-- TOC entry 3251 (class 2606 OID 16461)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: gabriel
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_id);


--
-- TOC entry 3247 (class 2606 OID 16414)
-- Name: classification classification_pk; Type: CONSTRAINT; Schema: public; Owner: gabriel
--

ALTER TABLE ONLY public.classification
    ADD CONSTRAINT classification_pk PRIMARY KEY (classification_id);


--
-- TOC entry 3249 (class 2606 OID 16434)
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: gabriel
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (inv_id);


--
-- TOC entry 3252 (class 2606 OID 16435)
-- Name: inventory fk_classification; Type: FK CONSTRAINT; Schema: public; Owner: gabriel
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES public.classification(classification_id) ON UPDATE CASCADE;
